apiVersion: v1
kind: PersistentVolume
metadata:
  name: neo4j-data-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-static
  nfs:
    server: "192.168.1.95"
    path: "/volume/173f30ca-9f55-43a7-bec1-2d7874f146d3/.srv/.unifi-drive/fast_drives/.data"
  mountOptions:
    - hard
    - nointr
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-data
  namespace: graphiti
spec:
  storageClassName: nfs-static
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: neo4j-data-pv
