apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-data
  namespace: graphiti
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
