apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: agent-code-review-egress
  namespace: agent-code-review
spec:
  endpointSelector: {}
  egress:
    - toFQDNs:
        - matchName: "api.openai.com"
        - matchName: "api.github.com"
        - matchName: "api.telegram.org"
        - matchPattern: "*.slack.com"
        - matchName: "slack.com"
        - matchName: "registry.npmjs.org"
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
    # Allow all HTTPS egress for npm install (CDN endpoints)
    - toCIDR:
        - 0.0.0.0/0
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
    # Graphiti MCP server (cluster-internal)
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: graphiti
            app: graphiti-mcp
      toPorts:
        - ports:
            - port: "8000"
              protocol: TCP
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
            - port: "53"
              protocol: TCP
  ingress: []
