version: "2"
linters:
  settings:
    errcheck:
      exclude-functions:
        - (*github.com/nixfleet/nixfleet/internal/ssh.Client).Exec
        - (*github.com/nixfleet/nixfleet/internal/ssh.Client).ExecSudo
        - (*github.com/nixfleet/nixfleet/internal/state.Manager).WriteState
        - (*github.com/nixfleet/nixfleet/internal/state.Manager).UpdateAfterApply
        - (*golang.org/x/sync/semaphore.Weighted).Acquire
        - (*golang.org/x/crypto/ssh.Session).Signal
        - fmt.Sscanf
        - (*os/exec.Cmd).Run
        - (*github.com/spf13/cobra.Command).MarkFlagRequired
        - (*encoding/json.Encoder).Encode
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - staticcheck
        text: SA5011
      - linters:
          - staticcheck
        text: S1039
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
