#!/bin/bash
#
# NixFleet ZFS-on-LUKS Partitioning Script
#
# Creates the partition layout for NixFleet Ubuntu hosts:
#   - EFI system partition (512 MB, FAT32)
#   - Boot partition (1 GB, ext4)
#   - ZFS root pool (remaining space) with keystore zvol (LUKS2)
#
# Environment:
#   DISK           Target disk (default: /dev/sda)
#   LUKS_PASSPHRASE  Initial LUKS passphrase for keystore (required)
#   HOSTNAME       Host name (used in pool naming, default: nixfleet)
#
# Usage:
#   DISK=/dev/sda LUKS_PASSPHRASE="..." bash zfs-partition.sh

set -euo pipefail

DISK="${DISK:-/dev/sda}"
HOSTNAME="${HOSTNAME:-nixfleet}"
LUKS_PASSPHRASE="${LUKS_PASSPHRASE:?LUKS_PASSPHRASE is required}"

log() { echo "[zfs-partition] $*"; }

# Safety check: only proceed if DISK is a valid block device
if [ ! -b "$DISK" ]; then
  echo "ERROR: $DISK is not a block device" >&2
  exit 1
fi

log "Partitioning $DISK for host $HOSTNAME"

# ============================================================================
# Step 1: Destroy existing pool if present, wipe partition table
# ============================================================================
zpool destroy rpool 2>/dev/null || true
wipefs -af "$DISK"
sgdisk --zap-all "$DISK"

# ============================================================================
# Step 2: Create partitions
# ============================================================================
log "Creating partitions..."
sgdisk -n1:1M:+512M -t1:EF00 -c1:"EFI" "$DISK"       # EFI System Partition
sgdisk -n2:0:+1G    -t2:8300 -c2:"boot" "$DISK"       # /boot
sgdisk -n3:0:0      -t3:BF00 -c3:"zfs"  "$DISK"       # ZFS rpool

# Wait for kernel to pick up new partition table
partprobe "$DISK"
sleep 2

# Determine partition device names (handle nvme vs sda naming)
if [[ "$DISK" == *nvme* ]] || [[ "$DISK" == *loop* ]]; then
  PART1="${DISK}p1"
  PART2="${DISK}p2"
  PART3="${DISK}p3"
else
  PART1="${DISK}1"
  PART2="${DISK}2"
  PART3="${DISK}3"
fi

# ============================================================================
# Step 3: Format EFI and boot partitions
# ============================================================================
log "Formatting EFI partition..."
mkfs.fat -F32 -n EFI "$PART1"

log "Formatting boot partition..."
mkfs.ext4 -L boot "$PART2"

# ============================================================================
# Step 4: Create ZFS pool
# ============================================================================
log "Creating ZFS pool rpool on $PART3..."
zpool create -f \
  -o ashift=12 \
  -o autotrim=on \
  -O compression=zstd \
  -O acltype=posixacl \
  -O xattr=sa \
  -O dnodesize=auto \
  -O normalization=formD \
  -O relatime=on \
  -O canmount=off \
  -O mountpoint=/ \
  -R /target \
  rpool "$PART3"

# ============================================================================
# Step 5: Create ZFS datasets
# ============================================================================
log "Creating ZFS datasets..."

# Root dataset
zfs create -o canmount=noauto -o mountpoint=/ rpool/ROOT
zfs create -o canmount=noauto -o mountpoint=/ rpool/ROOT/ubuntu
zfs mount rpool/ROOT/ubuntu

# Home
zfs create -o mountpoint=/home rpool/home

# Var datasets (for better snapshot/rollback granularity)
zfs create -o mountpoint=/var rpool/var
zfs create rpool/var/log
zfs create rpool/var/lib

# ============================================================================
# Step 6: Mount boot and EFI
# ============================================================================
log "Mounting boot and EFI..."
mkdir -p /target/boot
mount "$PART2" /target/boot
mkdir -p /target/boot/efi
mount "$PART1" /target/boot/efi

# ============================================================================
# Step 7: Create LUKS keystore zvol
# ============================================================================
log "Creating keystore zvol (64 MB)..."
zfs create -V 64M rpool/keystore

# Wait for zvol device to appear
sleep 2
KEYSTORE_DEV="/dev/zvol/rpool/keystore"
while [ ! -b "$KEYSTORE_DEV" ]; do
  log "Waiting for $KEYSTORE_DEV..."
  sleep 1
done

log "Formatting keystore with LUKS2..."
echo -n "$LUKS_PASSPHRASE" | cryptsetup luksFormat \
  --type luks2 \
  --label "keystore-$HOSTNAME" \
  --pbkdf argon2id \
  "$KEYSTORE_DEV" -

# ============================================================================
# Step 8: Write fstab entries for boot/EFI
# ============================================================================
log "Writing fstab..."
mkdir -p /target/etc
cat > /target/etc/fstab <<FSTAB
# Generated by NixFleet installer
$(blkid -s UUID -o value "$PART2" | xargs -I{} echo "UUID={}  /boot      ext4  defaults  0  2")
$(blkid -s UUID -o value "$PART1" | xargs -I{} echo "UUID={}  /boot/efi  vfat  umask=0077  0  1")
FSTAB

# ============================================================================
# Step 9: Write crypttab for TPM2 auto-unlock
# ============================================================================
log "Writing crypttab..."
cat > /target/etc/crypttab <<CRYPTTAB
# NixFleet keystore — TPM2 auto-unlock (enrolled on first boot)
keystore-rpool /dev/zvol/rpool/keystore none luks,discard,tpm2-device=auto
CRYPTTAB

log "Partitioning complete"
log "  Disk:      $DISK"
log "  EFI:       $PART1 (512 MB, FAT32)"
log "  Boot:      $PART2 (1 GB, ext4)"
log "  ZFS pool:  rpool on $PART3"
log "  Keystore:  rpool/keystore (64 MB, LUKS2)"
log "  Datasets:  rpool/ROOT/ubuntu, rpool/home, rpool/var"
